// Writes tests/templates.gen.ts: the instruction templates (.claude/better-tasks/*.md) as one object, for the
// tests' fake engine (the test runner can't read files). The plugin itself reads the .md files.
// Run: `bun scripts/templates.ts` writes it; `--check` exits 1 when it is stale.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const root = new URL('..', import.meta.url).pathname
const folder = `${root}.claude/better-tasks`
const outPath = `${root}tests/templates.gen.ts`

const files = Object.fromEntries(readdirSync(folder).filter(name => name.endsWith('.md')).sort().map(name => [name, readFileSync(`${folder}/${name}`, 'utf8')]))
const text = `// Generated by \`bun scripts/templates.ts\` from .claude/better-tasks/: don't edit by hand.\nexport const TEMPLATES: Record<string, string> = ${JSON.stringify(files, null, 2)}\n`

if (process.argv.includes('--check')) {
  const isCurrent = readFileSync(outPath, 'utf8') === text
  console.log(isCurrent ? 'templates: tests/templates.gen.ts is current' : 'templates: tests/templates.gen.ts is stale; run `bun scripts/templates.ts`')
  process.exit(isCurrent ? 0 : 1)
}
writeFileSync(outPath, text)
console.log(`templates: wrote ${outPath}`)
